export const ROUTE_PATH_HOME = '/'
export const ROUTE_PATH_LOGIN = '/dang-nhap'
export const ROUTE_PATH_FORGOTPASSWORD = '/quen-mat-khau'
export const ROUTE_PATH_CHANGEPASSWORD = '/doi-mat-khau'
export const ROUTE_TEST = '/test'
export const ROUTE_GIAO_AN = '/quan-ly-giao-an'
export const ROUTE_BAI_GIANG = '/quan-ly-bai-giang'

export const ROLE_DEFAULT = 'default'
export const ROLE_SUPERADMIN = 'superadmin'
export const ROLE_ADMIN = 'admin'
export const ROLE_TEACHER = 'giao-vien'
export const ROLE_PARENTOFSTUDENT = 'phu-huynh-hs'
