export const ROUTE_PATH_HOME = '/'
export const ROUTE_PATH_LOGIN = '/dang-nhap'
export const ROUTE_PATH_REGISTER = '/dang-ky'
export const ROUTE_PATH_FORGOTPASSWORD = '/quen-mat-khau'
export const ROUTE_PATH_CHANGEPASSWORD = '/doi-mat-khau'
export const ROUTE_TEST = '/test'
export const ROUTE_GIAO_AN = '/quan-ly-giao-an'
export const ROUTE_BAI_GIANG = '/quan-ly-bai-giang'
export const ROUTE_QT_HE_THONG = '/quan-tri-he-thong'

export const ROLE_DEFAULT = 'DEFAULT'
export const ROLE_SUPER_ADMIN = 'ROLE_SUPER_ADMIN'
export const ROLE_ADMIN = 'ROLE_ADMIN'
export const ROLE_TEACHER = 'ROLE_TEACHER'
export const ROLE_PARENTOFSTUDENT = 'ROLE_USER'
